### ISSUE TITLE
Web app crashes when reloading the /store page

### ISSUE THREAD

**Issue by ghsantos** [bidah/universal-medusa#3]
Appears to be related to IOScrollView from react-native-intersection-observer in packages/app/modules/products/components/infinite-products/index.tsx

```
error - /my-app/node_modules/react-native-intersection-observer/lib/index.js:1
import IntersectionObserver from './IntersectionObserver';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

**Comment by bidah** [comment]
Thanks for the finding @ghsantos 

You can fix it by adding to the end of the `next.config.js` file the missing package to transpile:

```js
  transpilePackages: [
    ...
    'react-native-intersection-observer',
  ],

```

Will be adding this to the next release of the `npx create-universal-medusa-app` as a fix 👍
